// <auto-generated />
namespace MvcProjeKampiDeneme.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_imagefile_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_imagefile_add));
        
        string IMigrationMetadata.Id
        {
            get { return "202111121434557_mig_imagefile_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
